FROM maven:3.8.4-openjdk-11 as base
COPY ./pom.xml ./pom.xml
COPY src src
RUN --mount=type=cache,target=/root/.m2,rw mvn package

FROM adoptopenjdk/openjdk11:alpine-jre
COPY --from=base target/notes-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java","-jar","app.jar"]
